Repository projectsyn/commodore-renovate, pull requests merged in 2021-12, with the labels that each got.

#4 Add Docker Image and CI/CD
  .github/workflows/push.yml
  .github/workflows/release.yml
  Dockerfile
  package.json
  src/index.ts
  tsconfig-build.json
Labels: enhancement

#6 Add missing GitHub config
  .github/PULL_REQUEST_TEMPLATE.md
  .github/changelog-configuration.json
  .ls-lint.yml
Labels: ignore

#7 Fix caching of Commodore results
  src/commodore/index.spec.ts
  src/commodore/inventory.ts
Labels: bug

#8 Update Commodore to v0.13.1
  requirements.txt
Labels: dependency
