Repository projectsyn/commodore-renovate, pull requests merged in 2022-01, with the labels that each got.

#10 Change `mergeConfig` to overwrite `RegExp` fields
  src/commodore/util.spec.ts
  src/commodore/util.ts
Labels: bug

#9 Query Lieutenant API for cluster facts
  package.json
  src/commodore/__fixtures__/5/global/commodore.yml
  src/commodore/__fixtures__/5/global/k3d.yml
  src/commodore/__fixtures__/5/tenant/c-foo-2.yml
  src/commodore/__fixtures__/5/tenant/c-foo-3.yml
  src/commodore/__fixtures__/5/tenant/renovate.commodore.json
  src/commodore/__fixtures__/5/tenant/test.yml
  src/commodore/__fixtures__/test.json
  src/commodore/__snapshots__/index.spec.ts.snap
  src/commodore/https-query.spec.ts
  src/commodore/https-query.ts
  src/commodore/index.spec.ts
  src/commodore/index.ts
  src/commodore/lieutenant.spec.ts
  src/commodore/lieutenant.ts
  src/commodore/readme.md
  src/commodore/types.ts
  src/index.ts
  yarn.lock
Labels: enhancement

#11 Expose Lieutenant token config only via environment variable
  src/commodore/index.ts
  src/commodore/readme.md
  src/index.ts
Labels: ignore

#12 Clean up log messages related to Lieutenant API
  src/commodore/index.ts
Labels: ignore

#13 Generate valid Commodore parameters for clusters with no dynamic facts
  package.json
  src/commodore/__snapshots__/index.spec.ts.snap
  src/commodore/index.spec.ts
  src/commodore/index.ts
  yarn.lock
Labels: bug

#14 Read Lieutenant API token from environment variable in Commodore manager
  src/commodore/index.spec.ts
  src/commodore/index.ts
  src/index.ts
Labels: bug

#15 Support renovating docker images in Commodore components
  src/commodore-docker/__fixtures__/1/params.yml
  src/commodore-docker/__fixtures__/2/params.yml
  src/commodore-docker/__fixtures__/3/params.yml
  src/commodore-docker/__snapshots__/index.spec.ts.snap
  src/commodore-docker/index.spec.ts
  src/commodore-docker/index.ts
  src/commodore-docker/readme.md
  src/index.ts
Labels: enhancement

#16 Recursively parse every object
  src/commodore-docker/__fixtures__/4/params.yml
  src/commodore-docker/__fixtures__/5/params.yml
  src/commodore-docker/__snapshots__/index.spec.ts.snap
  src/commodore-docker/index.spec.ts
  src/commodore-docker/index.ts
  src/commodore-docker/readme.md
Labels: ignore
